name: build
on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'koyeb-community'
    env:
      SCRIPT_DIR: /tmp/builder
    steps:
      - name: Set env
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          release=${GITHUB_REF#refs/*/}
          major=$(echo $release | awk -F \. {'print $1'})
          minor=$(echo $release | awk -F \. {'print $1 "." $2'})
          echo ::set-env name=RELEASE_VERSION::$release
          echo ::set-env name=RELEASE_MAJOR::$major
          echo ::set-env name=RELEASE_MINOR::$minor
      - uses: actions/checkout@v2
      - uses: chrisdickinson/setup-yq@v1.0.0
      - name: Login to GitHub Package Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - run: git clone git://github.com/koyeb-community/builder $SCRIPT_DIR
      - run: make -f $SCRIPT_DIR/builder.mk build
      - run: make -f $SCRIPT_DIR/builder.mk publish TAGS="$RELEASE_VERSION" TAGS+="$RELEASE_MAJOR" TAGS+="$RELEASE_MINOR"
